projeto/loja_app/urls.py
from django.urls import path
from loja_app.views import CreateProdutoView, DeleteProdutoView, DetailProdutoView, IndexView, ListMarcaView, CreateMarcaView, ListProdutoView, UpdateProdutoView


app_name = 'loja_app'

urlpatterns = [
    path('marca/', ListMarcaView.as_view(), name='list-marca'),
    path('marca/cadastro', CreateMarcaView.as_view(), name='create-marca'),
    

    path('', ListProdutoView.as_view(), name='list-produto'),
    path('produto/cadastro/', CreateProdutoView.as_view(), name='create-produto'),
    path('produto/<int:pk>/', DetailProdutoView.as_view(), name='detail-produto'),
    path('produto/<int:pk>/deletar/', DeleteProdutoView.as_view(), name='delete-produto'),
    path('produto/<int:pk>/update/', UpdateProdutoView.as_view(), name='update-produto'),
]

projeto/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('loja_app.urls')),
]

projeto/loja_app/models.py
from django.urls import reverse
from django.db import models

# Create your models here.
class Marca(models.Model):
    nome = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self) -> str:
        return self.nome

class Produto(models.Model):
    nome = models.CharField(max_length=100, null=False, blank=False)
    preco = models.FloatField(null=False, blank=False)
    descricao = models.TextField(null=False, blank=False, verbose_name="Descrição")
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.nome

    def get_absolute_url(self):
        return reverse("loja_app:detail-produto", kwargs={"pk": self.pk})

projeto/loja_app/views.py
from loja_app.models import Marca, Produto
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.urls import reverse_lazy

# Create your views here.

class IndexView(TemplateView):
    template_name = 'loja_app/base.html'

class ListMarcaView(ListView):
    model = Marca
    template_name = 'loja_app/marca/marca_list.html'

class CreateMarcaView(CreateView):
    model = Marca
    fields = '__all__'
    template_name = 'loja_app/marca/marca_form.html'
    success_url = reverse_lazy('loja_app:list-produto')


class ListProdutoView(ListView):
    model = Produto
    template_name = 'loja_app/produto/produto_list.html'

class CreateProdutoView(CreateView):
    model = Produto
    fields = '__all__'
    template_name = 'loja_app/produto/produto_form.html'
    success_url = reverse_lazy('loja_app:list-produto')

class DetailProdutoView(DetailView):
    model = Produto
    template_name = 'loja_app/produto/produto_detail.html'


class DeleteProdutoView(DeleteView):
    model = Produto
    success_url = reverse_lazy('loja_app:list-produto')
    template_name = 'loja_app/produto/produto_confirm_delete.html'

class UpdateProdutoView(UpdateView):
    model = Produto
    fields = '__all__'
    template_name = 'loja_app/produto/produto_form.html'

projeto/loja_app/templates/loja_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        
    {% block title %} {% endblock %}
    
    </title>
    <style>
        table, th, td {
          border: 1px solid black;
        }
        </style>
</head>
<body>
    <h1>Meu site django</h1>
    {% block content %} {% endblock %}

    <footer><p>Daniel de Oliveira</p></footer>
</body>
</html>

projeto/loja_app/templates/loja_app/marca/marca_form.html
{% extends 'loja_app/base.html' %}
{% load static %}

{% block title %}Cadastro{% endblock title %}

{% block content %}

    <h1>Cadastro Marca</h1>
    <div>

        <div>
            <div id="result"></div>
            <form id="form" name="form" method="POST">
                {% csrf_token %}
                <div >{{ form.as_p }}</div>
                <button type="submit">Enviar</button>
            </form>
            <a href="{%url 'loja_app:list-produto'%}">
                <button >Voltar</button>
            </a>
        </div>
        
    </div>
    
{% endblock content %}

projeto/loja_app/templates/loja_app/marca/marca_list.html
{% extends 'loja_app/base.html' %}

{% block title %}Marca{% endblock title %}

{% block content %}
    <h2>Lista das Marca</h2>
    {% for marca in object_list %}
    
        <p>{{marca}}</p>
        <p>--</p>

    {% endfor %}

{% endblock content %}

projeto/loja_app/templates/loja_app/produto/produto_confirm_delete.html
{% extends 'loja_app/base.html' %}

{% block title %}Deletar{% endblock title %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p>Tem certeza que quer deletar "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
    <a href="{% url 'loja_app:list-produto' %}"><button>Voltar</button></a>
{% endblock content %}

projeto/loja_app/templates/loja_app/produto/produto_detail.html
{% extends 'loja_app/base.html' %}

{% block title %}{{object}}{% endblock title %}


{% block content %}
    <h2>O produto</h2>
    <p>{{object.nome}}</p>
    <p>{{object.preco}}</p>
    <p>{{object.descricao}}</p>
    <p>{{object.marca}}</p>

    <a href="{% url 'loja_app:delete-produto' object.pk %}"><button>Deletar</button></a>
    <a href="{% url 'loja_app:update-produto' object.pk %}"><button>Atualizar</button></a>
    <p><a href="{% url 'loja_app:list-produto' %}"><button>Voltar</button></a></p>
{% endblock content %}

projeto/loja_app/templates/loja_app/produto/produto_form.html
{% extends 'loja_app/base.html' %}
{% load static %}

{% block title %}Cadastro{% endblock title %}

{% block content %}

    <h1>Cadastro Produto</h1>
    <div>

        <div>
            <div id="result"></div>
            <form id="form" name="form" method="POST">
                {% csrf_token %}
                <div >{{ form.as_p }}</div>
                <button type="submit">Enviar</button>
            </form>
            <a href="{%url 'loja_app:list-produto'%}">
                <button >Voltar</button>
            </a>
        </div>
        
    </div>
    
{% endblock content %}

projeto/loja_app/templates/loja_app/produto/produto_list.html
{% extends 'loja_app/base.html' %}

{% block title %}Produto{% endblock title %}

{% block content %}
    
    <a href="{% url 'loja_app:create-produto'%}"><button>Produto +</button></a>
    <a href="{% url 'loja_app:create-marca'%}"><button>Marca +</button></a>


    <h2>Lista das Produtos</h2>
    <table>
        <thead>
            <tr>
                <th>Nome</th>
                <th>Preço</th>
                <th>Marca</th>
                <th>Opções</th>
            </tr>
        </thead>
        {% for produto in object_list %}
        <tbody>
            <tr>
                <td>
                    <a href="{% url 'loja_app:detail-produto' produto.id %}">
                        {{produto.nome}}
                    </a>
                </td>
                <td>
                    {{produto.preco}}
                </td>
                <td>
                    {{produto.marca}}
                </td>
                <td>
                    <a href="{% url 'loja_app:delete-produto' produto.id %}"><button>Deletar</button></a>
                    <a href="{% url 'loja_app:update-produto' produto.id %}"><button>Atualizar</button></a>
                </td>
            </tr>
        </tbody>
        {% endfor %}

    </table>


{% endblock content %}